### ISSUE TITLE
"will be" language should be converted to MUST, SHOULD, or MAY

### ISSUE THREAD

**Issue by pmengelbert** [opencontainers/distribution-spec#85] opened 2020-01-28 21:11 UTC
Examples:
> All endpoints will be prefixed by the API version and the repository name:
> One or more errors will be returned in the following format:
> The code field will be a unique identifier, all caps with underscores by convention.
> A 404 Not Found response will be returned if the image is unknown to the registry.

Examples like the last one have impeded progress on the conformance tests, since most of the error codes are defined in terms of "will be" language, and we're unsure how much is simply conventional vs required by the spec.

**Comment by estesp** [comment] 2020-03-04 22:35
I think this issue is a duplicate of #27? Please comment if this isn't covered by that issue.

**Closed** 2020-03-04 22:36 UTC
