### ISSUE TITLE
Proposal: Limit the maximum number of lists returned by the tags list API

### ISSUE THREAD

**Issue by njucjc** [opencontainers/distribution-spec#533] opened 2024-04-01 08:36 UTC
`/v2/<name>/tags` api  will query all tags in the repo and load them into memory. If there are a large number of tags in the repo, there may be leading to OOM.

how about to limit the maximum number of entries returned by  the single tags list API like `/v2/_catalog` API and return `Link` for next page.

Related discussions:
https://github.com/distribution/distribution/discussions/4315#discussioncomment-8947556

**Comment by njucjc** [comment] 2024-04-01 11:08
This problem may be solved by [this PR](https://github.com/opencontainers/distribution-spec/pull/470)?

**Comment by sudo-bmitch** [comment] 2024-04-01 13:35
I believe this is a duplicate of #461.

**Closed** 2024-04-01 13:35 UTC
